-- Trigger Name: UPDATE_CAR_DETAILS
-- This trigger updates the availability flag, mileage, and location in the car table 
-- when the car is returned.

USE carRentalSystem;
DELIMITER $$

CREATE TRIGGER UPDATE_CAR_DETAILS
AFTER UPDATE ON BOOKING_DETAILS
FOR EACH ROW
BEGIN
    IF NEW.BOOKING_STATUS = 'C' THEN
        UPDATE CAR SET AVAILABILITY_FLAG = 'A', LOC_ID = NEW.PICKUP_LOC WHERE REGISTRATION_NUMBER = NEW.REG_NUM;
    ELSEIF COALESCE(NEW.ACT_RET_DT_TIME, 'NULL') <> 'NULL' THEN
        UPDATE CAR SET AVAILABILITY_FLAG = 'A', LOC_ID = NEW.DROP_LOC, MILEAGE = MILEAGE + GET_MILEAGE() WHERE REGISTRATION_NUMBER = NEW.REG_NUM;
    END IF;
END$$

CREATE FUNCTION GET_MILEAGE()
RETURNS DECIMAL(10, 2)
BEGIN
    DECLARE mileage DECIMAL(10, 2);
    SET mileage = ROUND(RAND() * (10000 - 100) + 100, 2);
    RETURN mileage;
END$$

DELIMITER ;
