DROP DATABASE IF EXISTS carrentalsystem;
create database carrentalsystem;
use carrentalsystem;
show databases; 
 
CREATE TABLE CUSTOMER_DETAILS
( DL_NUMBER VARCHAR(8) NOT NULL,
  FNAME VARCHAR(25) NOT NULL,
  LNAME VARCHAR(25) NOT NULL,
  PHONE_NUMBER DEC(10) NOT NULL,
  EMAIL_ID VARCHAR(30) NOT NULL,
  STREET VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) NOT NULL,
  STATE_NAME VARCHAR(20) NOT NULL,
  ZIPCODE DEC(5) NOT NULL,
  MEMBERSHIP_TYPE CHAR(3)DEFAULT 'No' NOT NULL,
  MEMBERSHIP_ID VARCHAR(5) DEFAULT NULL,
  CONSTRAINT CUSTOMERPK
  PRIMARY KEY (DL_NUMBER)
);

CREATE TABLE CAR_CATEGORY
( CATEGORY_NAME VARCHAR(25) NOT NULL,
  NO_OF_PERSON INTEGER NOT NULL,
  COST_PER_DAY DEC(5,2) NOT NULL,
  CONSTRAINT CARCATEGORYPK
  PRIMARY KEY (CATEGORY_NAME)
);

CREATE TABLE LOCATION_DETAILS
( LOCATION_ID CHAR(4) NOT NULL,
  LOCATION_NAME VARCHAR(50) NOT NULL,
  ZIPCODE DEC(5) NOT NULL,
  CONSTRAINT LOCATIONPK
  PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE CAR
( REGISTRATION_NUMBER CHAR(7) NOT NULL,
  MAKE VARCHAR(25) NOT NULL,
  MILEAGE INTEGER NOT NULL,
  CATEGORY_NAME VARCHAR(25) NOT NULL,
  LOC_ID CHAR(4) NOT NULL,
  AVAILABILITY_FLAG CHAR(1) NOT NULL,
  CONSTRAINT CARPK
  PRIMARY KEY (REGISTRATION_NUMBER),
  CONSTRAINT CARFK1
  FOREIGN KEY (CATEGORY_NAME) REFERENCES CAR_CATEGORY(CATEGORY_NAME),
  CONSTRAINT CARFK2
  FOREIGN KEY (LOC_ID) REFERENCES LOCATION_DETAILS(LOCATION_ID)
);

CREATE TABLE DISCOUNT_DETAILS
( DISCOUNT_CODE CHAR(4) NOT NULL,
  DISCOUNT_NAME VARCHAR(25) NOT NULL,
  EXPIRY_DATE DATE NOT NULL,
  DISCOUNT_PERCENTAGE DEC(4,2)  NOT NULL,
  CONSTRAINT DISCOUNTPK
  PRIMARY KEY (DISCOUNT_CODE),
  CONSTRAINT DISCOUNTSK
  UNIQUE (DISCOUNT_NAME)
);

CREATE TABLE RENTAL_CAR_INSURANCE
( INSURANCE_CODE CHAR(4) NOT NULL,
  INSURANCE_NAME VARCHAR(50) NOT NULL,
  COVERAGE_TYPE VARCHAR(200) NOT NULL,
  COST_PER_DAY DEC(4,2) NOT NULL,
  CONSTRAINT INSURANCEPK
  PRIMARY KEY (INSURANCE_CODE),
  CONSTRAINT INSURANCESK
  UNIQUE (INSURANCE_NAME)
);

CREATE TABLE BOOKING_DETAILS
( BOOKING_ID CHAR(5) NOT NULL,
  FROM_DT_TIME TIMESTAMP NOT NULL,
  RET_DT_TIME TIMESTAMP NOT NULL,
  AMOUNT DEC(10,2) NOT NULL,
  REG_NUM CHAR(7) NOT NULL,
  DL_NUM CHAR(8) NOT NULL,
  INS_CODE CHAR(4),
  DISCOUNT_CODE CHAR(4),
  CONSTRAINT BOOKINGPK
  PRIMARY KEY (BOOKING_ID),
  FOREIGN KEY (REG_NUM) REFERENCES CAR(REGISTRATION_NUMBER),
  CONSTRAINT BOOKINGFK4
  FOREIGN KEY (DL_NUM) REFERENCES CUSTOMER_DETAILS(DL_NUMBER),
  CONSTRAINT BOOKINGFK5
  FOREIGN KEY (INS_CODE) REFERENCES RENTAL_CAR_INSURANCE(INSURANCE_CODE),
  CONSTRAINT BOOKINGFK6
  FOREIGN KEY (DISCOUNT_CODE) REFERENCES DISCOUNT_DETAILS(DISCOUNT_CODE)
);

CREATE TABLE BILLING_DETAILS
( BILL_ID CHAR(6) NOT NULL,
  BILL_DATE DATE NOT NULL,
  DISCOUNT_AMOUNT DEC(10,2) NOT NULL,
  TOTAL_AMOUNT DEC(10,2) NOT NULL,
  BOOKING_ID CHAR(5) NOT NULL,
  CONSTRAINT BILLINGPK
  PRIMARY KEY (BILL_ID),
  CONSTRAINT BILLINGFK1
  FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING_DETAILS(BOOKING_ID)
);